// Use the clean data file (generated by scripts/fix-curation.mjs).
// curation.json is the human-editable source (supports inline (N) row tags).
// curation.data.json is the parsed, valid-JSON form the app reads.
import curation from "./curation.data.json";
import traitsData from "./traits.data.json";
import descriptionsData from "./descriptions.data.json";
import traitTotalsData from "./trait-totals.data.json";

/**
 * Get display name for a collection. Falls back to data name.
 */
export function getCollectionDisplayName(slug: string, dataName: string): string {
  return (curation.collectionNames as Record<string, string>)[slug] || dataName;
}

/**
 * Get display name for an artist. Falls back to data name.
 */
export function getArtistDisplayName(slug: string, dataName: string): string {
  return (curation.artistNames as Record<string, string>)[slug] || dataName;
}

/**
 * Get the ordered collection slugs for an artist.
 * Collections not in the list appear at the end in their original order.
 */
export function getCollectionOrder(artistSlug: string): string[] | null {
  return (curation.collectionOrder as unknown as Record<string, string[]>)[artistSlug] || null;
}

/**
 * Sort collections for an artist based on curation.json order.
 */
export function sortCollections<T extends { slug: string }>(artistSlug: string, collections: T[]): T[] {
  const order = getCollectionOrder(artistSlug);
  if (!order) return collections;

  return [...collections].sort((a, b) => {
    const ai = order.indexOf(a.slug);
    const bi = order.indexOf(b.slug);
    const aIdx = ai === -1 ? 999 : ai;
    const bIdx = bi === -1 ? 999 : bi;
    return aIdx - bIdx;
  });
}

/**
 * Check if a collection should be hidden from the site.
 */
export function isCollectionHidden(slug: string): boolean {
  const hidden = (curation as { hideCollections?: string[] }).hideCollections;
  return Array.isArray(hidden) && hidden.includes(slug);
}

/**
 * Get the curated order of artist slugs (from the spreadsheet import).
 * Returns null if not set, in which case caller should fall back to alphabetical.
 */
export function getArtistOrder(): string[] | null {
  const order = (curation as { artistOrder?: string[] }).artistOrder;
  return Array.isArray(order) && order.length > 0 ? order : null;
}

/**
 * Get the manual pieces-per-row for a collection. Returns null if not set.
 */
export function getPiecesPerRow(collectionSlug: string): number | null {
  const ppr = (curation as unknown as { piecesPerRow?: Record<string, number | string> }).piecesPerRow;
  if (!ppr) return null;
  const v = ppr[collectionSlug];
  return typeof v === "number" ? v : null;
}

/**
 * Get explicit row assignments for pieces in a collection.
 * Returns { pieceSlug: rowNumber } or null if no rows are tagged for this collection.
 * Pieces without an explicit row number will be auto-assigned after tagged rows.
 */
export function getPieceRows(collectionSlug: string): Record<string, number> | null {
  const rows = (curation as unknown as { pieceRows?: Record<string, Record<string, number>> }).pieceRows;
  if (!rows || !rows[collectionSlug]) return null;
  return rows[collectionSlug];
}

/**
 * Get the ordered piece slugs for a collection.
 */
export function getPieceOrder(collectionSlug: string): string[] | null {
  const po = (curation as { pieceOrder?: Record<string, string[]> }).pieceOrder;
  return (po as unknown as Record<string, string[]>)?.[collectionSlug] || null;
}

/**
 * Get the ordered list of featured hero piece slugs (for homepage rotation).
 * Returns an empty array if not set.
 */
export function getFeaturedHeroes(): string[] {
  const heroes = (curation as { featuredHeroes?: string[] }).featuredHeroes;
  return Array.isArray(heroes) ? heroes : [];
}

/**
 * Composite hero+sidebar layout config for a collection.
 * `heroPiece` slug is rendered as a (sidebarRows × sidebarRows) hero with
 * `sidebarCols × sidebarRows` smaller pieces beside it. Anything past that
 * spills into a regular justified gallery below.
 */
export interface HeroLayout {
  heroPiece: string;
  sidebarCols: number;
  sidebarRows: number;
  /** Optional explicit row-major ordering for the sidebar cells. */
  sidebarPieces?: string[];
}

export function getHeroLayout(collectionSlug: string): HeroLayout | null {
  const layouts = (curation as { heroLayouts?: Record<string, HeroLayout> }).heroLayouts;
  return layouts?.[collectionSlug] || null;
}

/**
 * Resolve the artist-website URL for a piece, using the collection's
 * template from curation.json ({tokenId} placeholder). Returns null if no
 * template is set or no tokenId is available.
 *
 * Special case: Grifters use xcopy.art's ARTWORK ID, not the on-chain
 * tokenId. The artwork id is parseable from the title ("Grifter #087" ->
 * grifter-87) and named legendaries (Rotten, etc.) live at a title-slug
 * URL (xcopy.art/works/grifters/rotten). The two diverge by a small,
 * non-constant offset because some on-chain tokenIds were skipped during
 * the Async Art mint - so we can't derive the artwork id from the tokenId.
 */
export function getArtistSiteUrl(
  collectionSlug: string,
  tokenId?: string,
  title?: string,
): string | null {
  if (collectionSlug === "grifters" && title) {
    const numbered = title.match(/^Grifter #0*(\d+)$/i);
    if (numbered) {
      return `https://xcopy.art/works/grifters/grifter-${numbered[1]}`;
    }
    const slug = title.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
    return slug ? `https://xcopy.art/works/grifters/${slug}` : null;
  }
  if (!tokenId) return null;
  const templates = (curation as { artistSiteTemplates?: Record<string, string> })
    .artistSiteTemplates;
  const tpl = templates?.[collectionSlug];
  if (!tpl) return null;
  return tpl.replace(/\{tokenId\}/g, tokenId);
}

/**
 * Get the edition shorthand for a collection (e.g. "1/1", "1/1/999").
 * Default is "1/1" - every piece is treated as unique unless the
 * collection is explicitly marked as a series in curation.json.
 *
 * Curation entry: `editions: { "fidenza": "1/1/999", ... }`
 */
export function getEditionType(collectionSlug: string): string {
  const editions = (curation as { editions?: Record<string, string> }).editions;
  return editions?.[collectionSlug] || "1/1";
}

/**
 * Get the filtered/ordered generative traits for a piece slug, or null if none.
 * Populated from on-chain metadata in scripts/build-traits-data.mjs.
 *
 * Values can be string, number, or string[] (used for Punks where a single
 * "Attribute" key has multiple values - one per accessory).
 */
export type TraitValue = string | number | string[];
export function getPieceTraits(slug: string): Array<[string, TraitValue]> | null {
  const data = traitsData as Record<string, Record<string, TraitValue>>;
  const row = data[slug];
  if (!row) return null;
  const entries = Object.entries(row);
  return entries.length > 0 ? entries : null;
}

/**
 * Get the per-piece description prose pulled from on-chain metadata, or null
 * if absent. Collection-level boilerplate (descriptions repeating across most
 * pieces in a collection) is filtered out at build time - only distinctive
 * per-piece prose survives.
 */
export function getPieceDescription(slug: string): string | null {
  const data = descriptionsData as Record<string, string>;
  return data[slug] || null;
}

/**
 * Per-collection clickability spec for trait keys / values. Drives two
 * surfaces:
 *   - Piece page Features panel: which trait values render as filter links
 *     vs plain catalogue-of-record text.
 *   - Collection page Browse-by-trait disclosure: which (key, value) pairs
 *     appear at all - the disclosure is the editorial pivot panel, so only
 *     clickable traits earn space there.
 *
 * Semantics for `CLICKABLE_TRAITS[slug][key]`:
 *   - "all"      → every value for this key is clickable / shown
 *   - string[]   → only these specific values are clickable / shown
 *   - undefined  → that key is not clickable / not in disclosure
 * Collection absent entirely from this map = no traits clickable / empty
 * disclosure. Default is conservative (whitelist-only) so a new collection
 * doesn't accidentally surface marketplace-style facet filtering on its
 * traits without explicit editorial decision.
 *
 * For multi-piece series only (1/1/x collections). 1/1 singletons skip the
 * map entirely because they have nothing to pivot to.
 */
export type ClickableRule = "all" | readonly string[];
export const CLICKABLE_TRAITS: Record<string, Record<string, ClickableRule>> = {
  cryptopunks: {
    Type: "all",
    Attribute: [
      "Big Beard",
      "Cap Forward",
      "Cowboy Hat",
      "Fedora",
      "Hoodie",
      "Police Cap",
      "Tiara",
      "Top Hat",
    ],
  },
  ringers: {
    Body: "all",
    Background: "all",
    "Peg style": ["Bullseye"],
    "Extra color": ["Red", "Green", "Blue"],
    Size: ["smol boi"],
  },
  fidenza: {
    Palette: "all",
    Scale: "all",
    Spiral: ["Yes"],
    "Super Blocks": ["Yes"],
    // "Shape Angles": ["Sharp"] - source has it; not yet extracted into
    // traits.data.json. Add once the build pipeline captures it.
  },
  "winds-of-yawanawa": {
    Origin: ["Uwa - Flower"],
    "Color Temperature": ["Scorching", "Freezing"],
  },
  "human-unreadable": {
    "Emotional Climate": "all",
  },
  "synthetic-dreams": {
    Cluster: "all",
  },
  "dataland-biome-lumina": {
    Type: "all",
  },
  "masks-of-luci": {
    Category: "all",
    "Attendee Type": "all",
  },
  "pxl-pod": {
    Pods: "all",
  },
  grifters: {
    Type: "all",
    // Array order is preserved as display order (Yellow / Blue / Green per
    // editorial spec, not the default count-desc sort).
    Color: ["Yellow", "Blue", "Green"],
    // Vision + Noise no longer render as standalone rows; their named-set
    // values surface under the synthetic "Sets" row defined in
    // SYNTHETIC_TRAIT_GROUPS below, alongside Wretch (also in Type).
  },
  // Explicit empty: traits display on the piece page but none are clickable,
  // and the collection page disclosure stays empty. Distinct from "absent"
  // because the empty map is an editorial decision documented here.
  "pxl-dex": {},
  qql: {},
};

/**
 * Trait keys to omit from the piece page Features panel entirely. Used when
 * an on-chain attribute is metadata that adds no signal for the reader
 * (PXL DEX exposes both "Pixels" and "Allowance" - only Pixels is the
 * holder-relevant figure).
 */
export const HIDDEN_TRAIT_KEYS: Record<string, readonly string[]> = {
  "pxl-dex": ["Allowance"],
};

/**
 * Collections whose Features panel doesn't render at all. Used when the
 * on-chain traits are licence / copyright boilerplate or one-off metadata
 * with no editorial value.
 */
export const TRAITS_FULLY_SUPPRESSED: ReadonlySet<string> = new Set([
  "lightyears",
  "lights",
  "skulls-of-luci",
]);

/**
 * Whether a specific (collection, key, value) pair should render as a
 * clickable filter link on the piece page Features panel.
 */
export function isTraitClickable(
  collectionSlug: string | undefined,
  key: string,
  value: string,
): boolean {
  if (!collectionSlug) return false;
  const spec = CLICKABLE_TRAITS[collectionSlug];
  if (!spec) return false;
  const rule = spec[key];
  if (rule === undefined) return false;
  if (rule === "all") return true;
  return rule.includes(value);
}

/**
 * Whether a specific trait key should appear at all on the piece page.
 * Honours HIDDEN_TRAIT_KEYS + TRAITS_FULLY_SUPPRESSED.
 */
export function isTraitKeyDisplayed(
  collectionSlug: string,
  key: string,
): boolean {
  if (TRAITS_FULLY_SUPPRESSED.has(collectionSlug)) return false;
  return !HIDDEN_TRAIT_KEYS[collectionSlug]?.includes(key);
}

/**
 * Synthetic traits added to every piece in a collection - used for editorial
 * facts not surfaced in on-chain metadata. QQL's "Minted by: Tyler Hobbs"
 * is editorial credit; it lives on the piece page like any other trait but
 * isn't pulled from traits.data.json. Prepended to the piece's actual traits
 * so it surfaces above the algorithmic features.
 */
export const SYNTHETIC_TRAITS: Record<string, Record<string, string>> = {
  qql: { "Minted by": "Tyler Hobbs" },
};

/**
 * Per-piece synthetic traits — for facts about a single piece that don't
 * belong on every piece in the collection. Used for physical companion
 * editions, one-off exhibition markers, and other single-piece attributes
 * that aren't in on-chain metadata. Merged in after the collection-level
 * synthetic traits and before the on-chain attributes.
 */
export const PIECE_SYNTHETIC_TRAITS: Record<string, Record<string, string>> = {
  // Punk 269 has a physical Paper Punk companion, exhibited at Kate Vass
  // Galerie's "Perfect & Priceless" show (2022). Marker trait; the article
  // link lives in the piece editorial file.
  "cryptopunks-269-3BBB": { "Paper Punk": "Yes" },
};

/**
 * Synthetic trait groups that render as their own row in the Browse-by-
 * trait disclosure but cut across multiple underlying trait keys. Used
 * for editorial groupings that don't map 1:1 to an on-chain trait
 * dimension - e.g., Grifters "Sets" surfaces named groups (Turbulence,
 * G to the M, Wretch) that span Vision / Noise / Type respectively.
 *
 * Each value carries its own label (what shows in the disclosure) plus
 * the (key, value) of the underlying real trait it filters by, so the
 * click destination is the same /collection/{slug}?trait=X&value=Y URL
 * a click on the real-trait row would produce. Counts come from the
 * facets map at render time.
 */
export type SyntheticTraitGroup = {
  label: string;
  values: {
    label: string;
    key: string;
    value: string;
    /** Optional explicit curated 3-piece list in the display order the
     *  reader should see (Yellow / Green / Blue for Grifters). Overrides
     *  the automatic "first-per-color" picker used for sets without an
     *  explicit list — needed when the fund holds >3 pieces matching the
     *  trait and the natural pieceOrder-first pick doesn't match the
     *  editorial selection. */
    pieces?: string[];
  }[];
};
export const SYNTHETIC_TRAIT_GROUPS: Record<string, SyntheticTraitGroup[]> = {
  grifters: [
    {
      label: "Sets",
      values: [
        { label: "Turbulence", key: "Vision", value: "Turbulence" },
        { label: "G to the M", key: "Noise", value: "G to the M" },
        { label: "Wretch", key: "Type", value: "Wretch" },
        {
          label: "Shady",
          key: "Type",
          value: "Shady",
          pieces: ["grifters-614-c1f3", "grifters-37-c1f3", "grifters-574-c1f3"],
        },
        {
          label: "Bubbles",
          key: "Atmosphere",
          value: "Bubbles",
          pieces: ["grifters-439-c1f3", "grifters-132-c1f3", "grifters-574-c1f3"],
        },
      ],
    },
  ],
};

// Back-compat alias used by older call sites; new code should use the
// CLICKABLE_TRAITS structure directly.
export const CURATED_TRAIT_VALUES = Object.fromEntries(
  Object.entries(CLICKABLE_TRAITS).map(([slug, spec]) => [
    slug,
    Object.fromEntries(
      Object.entries(spec)
        .filter(([, rule]) => Array.isArray(rule))
        .map(([key, rule]) => [key, rule as readonly string[]]),
    ),
  ]),
) as Record<string, Record<string, readonly string[]>>;

/**
 * Get the global collection-wide count for a (key, value) trait pair, or null
 * if no totals data exists for the collection or value. Used by the collection
 * page to render "15 of 146 Big Beards held" framing - so the reader sees not
 * just how many we own but how rare the trait is across the full collection.
 *
 * Source: src/lib/trait-totals.data.json. Currently populated for CryptoPunks
 * (canonical counts from Larva Labs); extensible to any collection where the
 * full trait distribution is publicly known.
 */
type TraitTotals = Record<string, {
  totalSupply: number;
  totals: Record<string, Record<string, number>>;
}>;
export function getTraitGlobalCount(
  collectionSlug: string,
  traitKey: string,
  traitValue: string
): number | null {
  const data = traitTotalsData as TraitTotals;
  return data[collectionSlug]?.totals?.[traitKey]?.[traitValue] ?? null;
}

/**
 * Sort pieces within a collection based on curation.json order.
 */
export function sortPieces<T extends { slug: string }>(collectionSlug: string, pieces: T[]): T[] {
  const order = getPieceOrder(collectionSlug);
  if (!order) return pieces;

  return [...pieces].sort((a, b) => {
    const ai = order.indexOf(a.slug);
    const bi = order.indexOf(b.slug);
    const aIdx = ai === -1 ? 999 : ai;
    const bIdx = bi === -1 ? 999 : bi;
    return aIdx - bIdx;
  });
}
