// Use the clean data file (generated by scripts/fix-curation.mjs).
// curation.json is the human-editable source (supports inline (N) row tags).
// curation.data.json is the parsed, valid-JSON form the app reads.
import curation from "./curation.data.json";

/**
 * Get display name for a collection. Falls back to data name.
 */
export function getCollectionDisplayName(slug: string, dataName: string): string {
  return (curation.collectionNames as Record<string, string>)[slug] || dataName;
}

/**
 * Get display name for an artist. Falls back to data name.
 */
export function getArtistDisplayName(slug: string, dataName: string): string {
  return (curation.artistNames as Record<string, string>)[slug] || dataName;
}

/**
 * Get the ordered collection slugs for an artist.
 * Collections not in the list appear at the end in their original order.
 */
export function getCollectionOrder(artistSlug: string): string[] | null {
  return (curation.collectionOrder as unknown as Record<string, string[]>)[artistSlug] || null;
}

/**
 * Sort collections for an artist based on curation.json order.
 */
export function sortCollections<T extends { slug: string }>(artistSlug: string, collections: T[]): T[] {
  const order = getCollectionOrder(artistSlug);
  if (!order) return collections;

  return [...collections].sort((a, b) => {
    const ai = order.indexOf(a.slug);
    const bi = order.indexOf(b.slug);
    const aIdx = ai === -1 ? 999 : ai;
    const bIdx = bi === -1 ? 999 : bi;
    return aIdx - bIdx;
  });
}

/**
 * Check if a collection should be hidden from the site.
 */
export function isCollectionHidden(slug: string): boolean {
  const hidden = (curation as { hideCollections?: string[] }).hideCollections;
  return Array.isArray(hidden) && hidden.includes(slug);
}

/**
 * Get the curated order of artist slugs (from the spreadsheet import).
 * Returns null if not set, in which case caller should fall back to alphabetical.
 */
export function getArtistOrder(): string[] | null {
  const order = (curation as { artistOrder?: string[] }).artistOrder;
  return Array.isArray(order) && order.length > 0 ? order : null;
}

/**
 * Get the manual pieces-per-row for a collection. Returns null if not set.
 */
export function getPiecesPerRow(collectionSlug: string): number | null {
  const ppr = (curation as unknown as { piecesPerRow?: Record<string, number | string> }).piecesPerRow;
  if (!ppr) return null;
  const v = ppr[collectionSlug];
  return typeof v === "number" ? v : null;
}

/**
 * Get explicit row assignments for pieces in a collection.
 * Returns { pieceSlug: rowNumber } or null if no rows are tagged for this collection.
 * Pieces without an explicit row number will be auto-assigned after tagged rows.
 */
export function getPieceRows(collectionSlug: string): Record<string, number> | null {
  const rows = (curation as unknown as { pieceRows?: Record<string, Record<string, number>> }).pieceRows;
  if (!rows || !rows[collectionSlug]) return null;
  return rows[collectionSlug];
}

/**
 * Get the ordered piece slugs for a collection.
 */
export function getPieceOrder(collectionSlug: string): string[] | null {
  const po = (curation as { pieceOrder?: Record<string, string[]> }).pieceOrder;
  return (po as unknown as Record<string, string[]>)?.[collectionSlug] || null;
}

/**
 * Get the ordered list of featured hero piece slugs (for homepage rotation).
 * Returns an empty array if not set.
 */
export function getFeaturedHeroes(): string[] {
  const heroes = (curation as { featuredHeroes?: string[] }).featuredHeroes;
  return Array.isArray(heroes) ? heroes : [];
}

/**
 * Resolve the artist-website URL for a piece, using the collection's
 * template from curation.json ({tokenId} placeholder). Returns null if no
 * template is set or no tokenId is available.
 */
export function getArtistSiteUrl(collectionSlug: string, tokenId?: string): string | null {
  if (!tokenId) return null;
  const templates = (curation as { artistSiteTemplates?: Record<string, string> })
    .artistSiteTemplates;
  const tpl = templates?.[collectionSlug];
  if (!tpl) return null;
  return tpl.replace(/\{tokenId\}/g, tokenId);
}

/**
 * Get the edition shorthand for a collection (e.g. "1/1", "1/1/999").
 * Default is "1/1" — every piece is treated as unique unless the
 * collection is explicitly marked as a series in curation.json.
 *
 * Curation entry: `editions: { "fidenza": "1/1/999", ... }`
 */
export function getEditionType(collectionSlug: string): string {
  const editions = (curation as { editions?: Record<string, string> }).editions;
  return editions?.[collectionSlug] || "1/1";
}

/**
 * Sort pieces within a collection based on curation.json order.
 */
export function sortPieces<T extends { slug: string }>(collectionSlug: string, pieces: T[]): T[] {
  const order = getPieceOrder(collectionSlug);
  if (!order) return pieces;

  return [...pieces].sort((a, b) => {
    const ai = order.indexOf(a.slug);
    const bi = order.indexOf(b.slug);
    const aIdx = ai === -1 ? 999 : ai;
    const bIdx = bi === -1 ? 999 : bi;
    return aIdx - bIdx;
  });
}
