/**
 * Curation layer helpers. Reads from curation.data.json (generated by
 * scripts/fix-curation.mjs from the human-editable curation.json).
 * See reference/ARCHITECTURE.md for what belongs here vs data.ts vs
 * content/editorial/.
 */
import curation from "./curation.data.json";
import traitsData from "./traits.data.json";
import descriptionsData from "./descriptions.data.json";
import traitTotalsData from "./trait-totals.data.json";

// --- Display names -------------------------------------------------------

export function getCollectionDisplayName(slug: string, dataName: string): string {
  return (curation.collectionNames as Record<string, string>)[slug] || dataName;
}
export function getArtistDisplayName(slug: string, dataName: string): string {
  return (curation.artistNames as Record<string, string>)[slug] || dataName;
}

// --- Ordering ------------------------------------------------------------

export function getCollectionOrder(artistSlug: string): string[] | null {
  return (curation.collectionOrder as unknown as Record<string, string[]>)[artistSlug] || null;
}

export function sortCollections<T extends { slug: string }>(artistSlug: string, collections: T[]): T[] {
  const order = getCollectionOrder(artistSlug);
  if (!order) return collections;
  return [...collections].sort((a, b) => {
    const ai = order.indexOf(a.slug);
    const bi = order.indexOf(b.slug);
    return (ai === -1 ? 999 : ai) - (bi === -1 ? 999 : bi);
  });
}

export function getArtistOrder(): string[] | null {
  const order = (curation as { artistOrder?: string[] }).artistOrder;
  return Array.isArray(order) && order.length > 0 ? order : null;
}

export function getPieceOrder(collectionSlug: string): string[] | null {
  const po = (curation as { pieceOrder?: Record<string, string[]> }).pieceOrder;
  return po?.[collectionSlug] || null;
}

export function sortPieces<T extends { slug: string }>(collectionSlug: string, pieces: T[]): T[] {
  const order = getPieceOrder(collectionSlug);
  if (!order) return pieces;
  return [...pieces].sort((a, b) => {
    const ai = order.indexOf(a.slug);
    const bi = order.indexOf(b.slug);
    return (ai === -1 ? 999 : ai) - (bi === -1 ? 999 : bi);
  });
}

// --- Layout hints --------------------------------------------------------

export function getPiecesPerRow(collectionSlug: string): number | null {
  const ppr = (curation as unknown as { piecesPerRow?: Record<string, number> }).piecesPerRow;
  return typeof ppr?.[collectionSlug] === "number" ? ppr[collectionSlug]! : null;
}

export function getPieceRows(collectionSlug: string): Record<string, number> | null {
  const rows = (curation as unknown as { pieceRows?: Record<string, Record<string, number>> }).pieceRows;
  return rows?.[collectionSlug] || null;
}

export interface HeroLayout {
  heroPiece: string;
  sidebarCols: number;
  sidebarRows: number;
  sidebarPieces?: string[];
}

export function getHeroLayout(collectionSlug: string): HeroLayout | null {
  const layouts = (curation as { heroLayouts?: Record<string, HeroLayout> }).heroLayouts;
  return layouts?.[collectionSlug] || null;
}

// --- Visibility ----------------------------------------------------------

export function isCollectionHidden(slug: string): boolean {
  const hidden = (curation as { hideCollections?: string[] }).hideCollections;
  return Array.isArray(hidden) && hidden.includes(slug);
}

// --- Editions ------------------------------------------------------------

export function getEditionType(collectionSlug: string): string {
  const editions = (curation as { editions?: Record<string, string> }).editions;
  return editions?.[collectionSlug] || "1/1";
}

// --- Artist-site URL templates -------------------------------------------

/**
 * Resolve the artist-website URL for a piece. Template lookup in
 * curation.json → artistSiteTemplates[collectionSlug]. `{tokenId}` is
 * substituted.
 *
 * Add a collection-specific override here if the artist site uses a
 * non-tokenId identifier (e.g. XCOPY's Grifters use an artwork number
 * that differs from the token id).
 */
export function getArtistSiteUrl(collectionSlug: string, tokenId?: string, _title?: string): string | null {
  if (!tokenId) return null;
  const templates = (curation as { artistSiteTemplates?: Record<string, string> }).artistSiteTemplates;
  const tpl = templates?.[collectionSlug];
  if (!tpl) return null;
  return tpl.replace(/\{tokenId\}/g, tokenId);
}

// --- Traits --------------------------------------------------------------

export type TraitValue = string | number | string[];

export function getPieceTraits(slug: string): Array<[string, TraitValue]> | null {
  const data = traitsData as Record<string, Record<string, TraitValue>>;
  const row = data[slug];
  if (!row) return null;
  const entries = Object.entries(row);
  return entries.length > 0 ? entries : null;
}

export function getPieceDescription(slug: string): string | null {
  return (descriptionsData as Record<string, string>)[slug] || null;
}

/**
 * Per-collection clickability spec for trait keys / values.
 *   - "all"     — every value clickable
 *   - string[]  — value-level whitelist (preserves array order as display order)
 *   - undefined — key not clickable, hidden from the disclosure panel
 * Collection absent entirely = no traits clickable.
 *
 * Example (Fidenza):
 *   fidenza: { Palette: "all", Density: "all" }
 * Example (curated subset):
 *   punks: { Type: "all", Attribute: ["Big Beard", "Cap Forward", "Hoodie"] }
 */
export type ClickableRule = "all" | readonly string[];
export const CLICKABLE_TRAITS: Record<string, Record<string, ClickableRule>> = {};

/** Trait keys to omit entirely from the piece-page Features panel. */
export const HIDDEN_TRAIT_KEYS: Record<string, readonly string[]> = {};

/** Collections whose Features panel is suppressed entirely. */
export const TRAITS_FULLY_SUPPRESSED = new Set<string>();

export function isTraitClickable(
  collectionSlug: string | undefined,
  key: string,
  value: string,
): boolean {
  if (!collectionSlug) return false;
  const rule = CLICKABLE_TRAITS[collectionSlug]?.[key];
  if (rule === undefined) return false;
  if (rule === "all") return true;
  return rule.includes(value);
}

/**
 * Collection-wide rarity count for a trait value. Returns null if not
 * populated. Sourced from trait-totals.data.json via fetch-trait-totals.mjs.
 */
export function getTraitGlobalCount(
  collectionSlug: string,
  key: string,
  value: string,
): number | null {
  const data = traitTotalsData as Record<string, Record<string, Record<string, number>>>;
  return data[collectionSlug]?.[key]?.[value] ?? null;
}

// --- Synthetic trait groups ---------------------------------------------

/**
 * Editorially-defined trait groups that span multiple underlying keys.
 * E.g. Grifters "Sets" spans Vision + Noise + Type + Atmosphere; clicking
 * a set applies the underlying (key, value) filter with `set=1` in the URL
 * so the collection page reduces to the curated pieces list.
 *
 * See reference/FILTER.md for the reader-facing semantics.
 */
export type SyntheticTraitGroup = {
  label: string;
  values: {
    label: string;
    key: string;
    value: string;
    /** Optional explicit curated piece list in display order. When
     *  present, the collection page renders these pieces (in this order)
     *  when the set is active. Skips the auto-picker. */
    pieces?: string[];
  }[];
};

export const SYNTHETIC_TRAIT_GROUPS: Record<string, SyntheticTraitGroup[]> = {};
