/**
 * On-chain source layer. See reference/ARCHITECTURE.md.
 *
 * Regenerated by scripts/import-portfolio.mjs from your portfolio spreadsheet.
 * Manual edits below are lost on the next import. Anything editorial
 * (curator notes, display order, hide flags) belongs in curation.json or
 * content/editorial/, not here.
 */

export interface Artist {
  slug: string;
  name: string;
  bio?: string;
  portrait?: string;
  wallet?: string;
  externalUrl?: string;
  tags?: string[];
}

export interface Collection {
  slug: string;
  name: string;
  artistSlug: string;
  description?: string;
  contractAddress?: string;
  totalSupply?: number;
  mintDate?: string;
  platform?: string;
  /** Optional. Prefer curator notes in content/editorial/collections/. */
  curatorNote?: string;
  /** Optional. Verbatim artist words. Never editorialized. */
  artistStatement?: string;
  exhibitions?: {
    date: string;
    title: string;
    location?: string;
    url?: string;
    pieces?: string[];
  }[];
}

export interface Piece {
  id: string;
  slug: string;
  title: string;
  collectionSlug: string;
  artistSlug: string;
  image?: string;
  medium: "image" | "video" | "interactive" | "physical";
  description?: string;
  traits?: Record<string, string | number | string[]>;
  tokenId?: string;
  contractAddress?: string;
  mintDate?: string;
  mintPlatform?: string;
  year?: string;
  openseaUrl?: string;
  originalUri?: string;
}

// Starter — replace with your fund's holdings.
export const artists: Artist[] = [];
export const collections: Collection[] = [];
export const pieces: Piece[] = [];

// --- Lookup helpers ------------------------------------------------------

export const getArtist = (slug: string) => artists.find((a) => a.slug === slug);
export const getCollection = (slug: string) => collections.find((c) => c.slug === slug);
export const getPiece = (slug: string) => pieces.find((p) => p.slug === slug);
export const getCollectionsByArtist = (artistSlug: string) =>
  collections.filter((c) => c.artistSlug === artistSlug);
export const getPiecesByCollection = (collectionSlug: string) =>
  pieces.filter((p) => p.collectionSlug === collectionSlug);
export const getPiecesByArtist = (artistSlug: string) =>
  pieces.filter((p) => p.artistSlug === artistSlug);
